### ISSUE TITLE
Node JS SDK NPM Run start Error

### ISSUE THREAD

**Issue by cahyosubroto** [elevenlabs/elevenlabs-js#31]
When install Node JS SDK, I encounter an error.

Steps to reproduce:
1. In node folder, run npm install and fill the .env file.
2. Run npm run start or npx tsx src/index. It should return the following error
```
> start
> tsx src/index.ts

xxx\node_modules\elevenlabs\api\resources\pronunciationDictionary\client\Client.js:98
                        throw new errors.ElevenLabsError({
                              ^

ElevenLabsError: Status code: 400
Body: {
  "detail": {
    "status": "Unable to parse lexicon file",
    "message": "Unable to parse lexicon file. Lexicon file formatted incorrectly"
  }
}
    at PronunciationDictionary.<anonymous> xxx\node_modules\elevenlabs\api\resources\pronunciationDictionary\client\Client.js:98:31)
    at Generator.next (<anonymous>)
    at fulfilled (xxx\node_modules\elevenlabs\api\resources\pronunciationDictionary\client\Client.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 400,
  body: {
    detail: {
      status: 'Unable to parse lexicon file',
      message: 'Unable to parse lexicon file. Lexicon file formatted incorrectly'
    }
  }
}

Node.js v18.16.0
```

**Comment by dsinghvi** [comment]
@cahyosubroto this looks like an issue with the `lexicon file` or the core API -- i'm going to close this issue since issues here are generally scoped to the TypeScript SDK!
