### ISSUE TITLE
bun support

### ISSUE THREAD

**Issue by hexxt-git** [elevenlabs/elevenlabs-js#87]
i can't express enough my disappointment when i found out this library doesn't support bun 

```js
4 |  */
5 | Object.defineProperty(exports, "__esModule", { value: true });
6 | exports.ElevenLabsError = void 0;
7 | class ElevenLabsError extends Error {
8 |     constructor({ message, statusCode, body }) {
9 |         super(buildMessage({ message, statusCode, body }));
            ^
error: This function is only supported in node environments. bun is not supported
      at new ElevenLabsError (/home/hexxt/Documents/GitHub/Artificial-Intelligence-Agent/node_modules/elevenlabs/errors/ElevenLabsError.js:9:9)
      at /home/hexxt/Documents/GitHub/Artificial-Intelligence-Agent/node_modules/elevenlabs/wrapper/play.js:33:19
      at /home/hexxt/Documents/GitHub/Artificial-Intelligence-Agent/node_modules/elevenlabs/wrapper/play.js:8:71
      at new Promise (:1:11)
      at /home/hexxt/Documents/GitHub/Artificial-Intelligence-Agent/node_modules/elevenlabs/wrapper/play.js:4:12
      at play (/home/hexxt/Documents/GitHub/Artificial-Intelligence-Agent/node_modules/elevenlabs/wrapper/play.js:31:12)
      at /home/hexxt/Documents/GitHub/Artificial-Intelligence-Agent/tts.js:44:9
```

**Comment by dsinghvi** [comment]
@hexxt-git want to submit a PR here to allow it for bun https://github.com/elevenlabs/elevenlabs-js/blob/main/src/wrapper/play.ts ? This only applies to the `play` function

**Comment by hexxt-git** [comment]
> @hexxt-git want to submit a PR here to allow it for bun https://github.com/elevenlabs/elevenlabs-js/blob/main/src/wrapper/play.ts ? This only applies to the `play` function

not really up to work for free to a paid api. but you sound interested maybe you should give it a go
